sudo: required
services:
  - docker

before_install:
  - docker build -t p0m1d0rka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e 'CI=true' p0m1d0rka/react-test npm run test -- --coverage

after_success:
  # build production images
  - docker build -t p0m1d0rka/multi-client:1.0.0 ./client
  - docker build -t p0m1d0rka/multi-nginx:1.0.0 ./nginx
  - docker build -t p0m1d0rka/multi-server:1.0.0 ./server
  - docker build -t p0m1d0rka/multi-worker:1.0.0 ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push p0m1d0rka/multi-client:1.0.0 
  - docker push p0m1d0rka/multi-nginx:1.0.0 
  - docker push  p0m1d0rka/multi-server:1.0.0 
  - docker push p0m1d0rka/multi-worker:1.0.0 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  # look at S3
  bucket_name: "elasticbeanstalk-us-east-1-625295982156"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"